version: '3.1'
services:
  classify:
    build: .
    image: mtf-cron-parser
    environment:
      - MATIFY_API_ENDPOINT='http://server:8000'

networks:
  default:
    external:
      name: matifysite_backend
