version: '3.1'
services:
  autoparser:
    build: .
    restart: always
    image: mtf-cron-parser
    environment:
      - MATIFY_API_ENDPOINT=https://matify.net/

networks:
  default:
    external:
      name: matifysite_backend
